#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

/**
 * Registers Auto Loader to use with Composer
 * --------------------------------------------------------
 * 
 * These files will be generated the first time the
 * application loads.
 */

require __DIR__ . '/vendor/autoload.php';

/**
 * Loads all commands needed for Tick to work
 */

 use Tick\App;

 $app = new App();
 $app->run_tick_commands($argv);